# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 22, host: 22230, id: "ssh"
  config.vm.network :forwarded_port, guest: 9000, host: 9000, id: "kibana"
  config.vm.network :forwarded_port, guest: 5601, host: 5601, id: "kibanav4"
  config.vm.network :forwarded_port, guest: 9200, host: 9200, id: "elasticsearch"
  config.vm.provision :shell, :path => "deploy/deploy.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
