# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.provision :shell, :path => "deploy/deploy.sh"
  config.vm.network :forwarded_port, guest: 22, host: 22222, id: "ssh"
  config.vm.provider :virtualbox do |vb|
    vb.name = "ensembl_virtual_machine_74"
  end
end
