# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Set the Ensembl version here
ENSEMBL_API_VERSION = ENV['ENSEMBL_API_VERSION'] || "74"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision :shell, :path => "deploy/deploy.sh", :args => "#{ENSEMBL_API_VERSION} #{ENV['GUI']}"
  config.vm.network :forwarded_port, guest: 22, host: 22222, id: "ssh"
  config.vm.provider :virtualbox do |vb|
    vb.name = "ensembl_virtual_machine_#{ENSEMBL_API_VERSION}"
    if ENV['GUI']
      vb.gui = true
    end
    
    # Give it 1GB of RAM
    vb.memory = 1024
  end
end
