# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  # config.vm.network :hostonly, "192.168.242.2"
  config.vm.network :forwarded_port, host: 3306, guest: 3306, id: "maria"
  config.vm.network :forwarded_port, guest: 22, host: 2229, id: "ssh"
  config.vm.provision :shell, :path => "deploy/deploy.sh"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "mariadb_32bit"
  end
end
