# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "f500/ubuntu-lucid64"
  # config.vm.network :hostonly, "192.168.242.2"
  config.vm.network :forwarded_port, host: 3307, guest: 3306
  config.vm.network :forwarded_port, guest: 22, host: 2230, id: "ssh"
  config.vm.provision :shell, :path => "deploy/deploy.sh"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "mysql_32bit"
  end
end
