# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Set the Ensembl version here
ENSEMBL_API_VERSION = ENV['ENSEMBL_API_VERSION'] || "76"

# Set TEST_ENV to nothing to stop deploying a MariaDB along with your server
TEST_ENV = 'true'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  # :guest == VM
  # :host == local machine
  config.vm.network :forwarded_port, id: "ssh", host: 2250, guest: 22
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  config.vm.synced_folder "rest-src/", "/home/vagrant/src", :create => true
  
  config.vm.provision "shell", path: "deploy/deploy.sh", :args => "#{ENSEMBL_API_VERSION} #{TEST_ENV}"
end
